version: '3.8'

services:

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/redis

  redis-queue:
    build: .
    container_name: redis-queue
    command: rq worker --url redis://redis:6379
    links:
      - redis
    depends_on:
      - redis

  gunicorn-app:
    container_name: gunicorn-app
    build: .
    restart: on-failure
    command: python server.py
    environment:
      REDIS_HOST: redis
      GUNICORN_HOST: 0.0.0.0
      GUNICORN_PORT: 8080
      GUNICORN_WORKERS: 1
    ports:
      - '8080:8080'
    depends_on:
      - redis-queue