openapi: 3.0.0
info:
  title: API Resize Image
  version: '1.0'
  description: Documentação da API REST para redimensionamento de imagem
  contact:
    email: moreirandanilo@gmail.com
tags:
  - name: Imagens
    description: Serviços relativos ao processamento de Imagens
paths:
  /resize:
    post:
      tags:
        - Imagens
      summary: Envia uma imagem para redimensionamento
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '201':
          description: Imagem enviada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
        '400':
          description: Requisição inválida
  /resize/{job_id}:
    get:
      tags:
        - Imagens
      summary: Envia uma imagem para redimensionamento
      parameters:
        - in: path
          required: true
          name: job_id
          description: Identificador da tarefa de redimensionamento da imagem
          schema:
            type: string
      responses:
        '200':
          description: Imagem retornada com sucesso
          content:
            image/png:
              schema:
                type: string
                format: binary
        '400':
          description: Requisição inválida
